module.exports = {
  content: ["**/*.html"],
  whitelist: [
    "fa",
    "fa-envelope",
    "is-active",
    "is-outlined",
    "enhanced",
    "lazy-background",
    "aos-init",
    "aos-animate",
    "is-info",
    "is-primary",
    "cookie-banner",
    "cookie-banner__content",
    "cookie-banner__text",
    "cookie-banner__buttons",
    "cookie-banner__accept-button",
    "cookie-banner__info-button",
    "hero",
    "hero-body",
  ],
};
